spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Aliyun_rds_123456
    url: jdbc:mysql://rm-bp1f65ehm719kd63y5o.mysql.rds.aliyuncs.com:3306/mybatis-plus?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: keqi