spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Aliyun_rds_123456
    url: jdbc:mysql://rm-bp1f65ehm719kd63y5o.mysql.rds.aliyuncs.com:3306/datax_source_a?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: keqi

knife4j:
  enable: true

logging:
  file:
    name: logs/app.log
  level:
    com:
      keqi: debug