# 公共环境配置可以放在此文件中

spring:
    profiles:
        active: local-dev
    main:
        banner-mode: off

# 配置端口号和应用路径
server:
    port: 21803
    servlet:
        context-path: /seed

# sa-token 相关配置
sa-token:
    is-print: false
    is-read-cookie: false
    token-style: tik
    is-concurrent: false
    token-name: token

# 关闭 mybatis-plus banner
mybatis-plus:
    global-config:
        banner: false