# 本机开发环境

# 配置数据源信息(此处使用了 p6spy 插件统计 SQL 执行时间，仅用于开发阶段)
spring:
    datasource:
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        password: Aliyun_rds_123456
        url: jdbc:p6spy:mysql://rm-bp1f65ehm719kd63y5o.mysql.rds.aliyuncs.com:3306/project-seed-4?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
        username: keqi

# 配置日志文件
logging:
    level:
        com:
            keqi: debug

knife4j:
    enable: true
