spring:
  redis:
    url: redis://user:123456@47.102.124.165:6379
    lettuce: # 如果不加上这个配置，就相当于没有给Redis指定连接池
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1ms
        max-idle: 8
#    # Redis 集群配置
#    cluster:
#      max-redirects: 3
#      nodes:
#        - 192.168.59.32:6379
#        - 192.168.59.32:6379
#        - 192.168.59.32:6379
#        - 192.168.59.32:6379
#        - 192.168.59.32:6379
#        - 192.168.59.32:6379

#    # Redis 主从/哨兵配置
#    sentinel:
#      master: mymaster
#      nodes:
#        - 192.168.59.32:6379
#        - 192.168.59.32:6379
#        - 192.168.59.32:6379