spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:9091 # 服务端地址
management:
  endpoints:
    web:
      exposure:
        include: '*' #开放所有端点
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file:
    name: client.log